"""add topic priority level

Revision ID: 98b3e45e40cb
Revises: a9bc9bec8eaf
Create Date: 2026-09-18 22:36:43.845917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '98b3e45e40cb'
down_revision: Union[str, Sequence[str], None] = 'a9bc9bec8eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('priority_level', sa.String(length=50), nullable=True))
    op.alter_column('topics', 'priority_score',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topics', 'priority_score',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.drop_column('topics', 'priority_level')
    # ### end Alembic commands ###
