"""create keyword metrics table

Revision ID: a9bc9bec8eaf
Revises: c250a47a624d
Create Date: 2026-09-18 03:04:45.607619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bc9bec8eaf'
down_revision: Union[str, Sequence[str], None] = 'c250a47a624d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('keyword_difficulty', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('competition', sa.String(length=100), nullable=True),
    sa.Column('serp_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_metrics_topic_id'), 'keyword_metrics', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_metrics_topic_id'), table_name='keyword_metrics')
    op.drop_table('keyword_metrics')
    # ### end Alembic commands ###
