"""create topics table

Revision ID: c250a47a624d
Revises: 4567e9988b27
Create Date: 2026-09-18 02:09:17.774793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c250a47a624d'
down_revision: Union[str, Sequence[str], None] = '4567e9988b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('keyword_ideas', sa.JSON(), nullable=False),
    sa.Column('search_intent', sa.String(length=100), nullable=False),
    sa.Column('business_value', sa.String(length=100), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_website_id'), 'topics', ['website_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_website_id'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
